name: Daily Summary Generation

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM UTC daily
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  trigger-task:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger daily task with retry
        run: |
          max_attempts=5
          attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts"
          
            response=$(curl -s -o /dev/null -w "%{http_code}" \
              --max-time 500 \
              -X POST \
              -H "x-internal-token: ${{ secrets.CRON_SECRET }}" \
              "https://market-forge.onrender.com/api/articles")
          
            if [ $response -eq 200 ]; then
              echo "Success!"
              exit 0
            fi
          
            echo "Failed with status $response, waiting 60s before retry..."
            sleep 60
            attempt=$((attempt + 1))
          done
          
          echo "All attempts failed"
          exit 1
